Books/urls.py
from django.urls import path

from . import views

app_name = "Books"

urlpatterns = [
    path('book_list/', views.BookListView.as_view(), name='book_list'),
    path('update_book/<int:book_id>/', views.UpdateBookView.as_view(), name='update_book'),
    path('borrow_history/', views.BorrowHistoryView.as_view(), name='borrow_history'),
    path('create_book/', views.CreateBookView.as_view(), name='create_book'),
    path('confirm_delete_book/<int:book_id>/', views.ConfirmDeleteBookView.as_view(), name='confirm_delete_book'),
    path('book_detail/<int:book_id>/', views.book_detail, name='book_detail'),
    path('borrow_requests/', views.ManageBorrowRequestsView.as_view(), name='borrow_requests'),
    path('search/', views.SearchResultsView.as_view(), name='search_results'),
    path('authors/', views.AuthorListView.as_view(), name='author_list'),
    path('authors/create/', views.AuthorsCreate.as_view(), name='author_form'),
    path('genres/', views.GenreListView.as_view(), name='genre_list'),
    path('genres/create/', views.GenreCreate.as_view(), name='genre_create'),
    path('authors/<int:pk>/edit/', views.AuthorEditView.as_view(), name='author_edit'),
    path('genres/<int:pk>/edit/', views.GenreEditView.as_view(), name='genre_edit'),
    path('authors/<int:pk>/delete/', views.AuthorDeleteView.as_view(), name='author_delete'),
    path('genres/<int:pk>/delete/', views.GenreDeleteView.as_view(), name='genre_delete'),

]

Library_System/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('home/', views.home, name='home'),
    path('', include('Users.urls')),
    path('', include('Books.urls')),

]

Users/urls.py
from django.urls import path
from . import views

app_name = "Users"

urlpatterns = [
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('register/', views.RegistrationView.as_view(), name='register'),
    path('librarian_menu/', views.LibrarianMenuView.as_view(), name='librarian_menu'),
    path('user_office/', views.UserOfficeView.as_view(), name='user_office'),
    path('edit_profile/<int:pk>/', views.EditProfileView.as_view(), name='edit_profile'),
    path('change_passord/', views.ChangePasswordView.as_view(), name='change_password'),
    path('delete_profile/<int:pk>/', views.DeleteUserProfile.as_view(), name='delete_profile')
]

Users/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Author(models.Model):
    name=models.CharField(max_length=255)
    bio=models.TextField()
     
    def __str__(self):
        return self.name
    

class Genre(models.Model):
    name=models.CharField(max_length=255)

    def __str__(self):
        return self.name
    

class Book(models.Model):
    title = models.CharField(max_length=255)  
    summary = models.TextField()  
    isbn = models.CharField(max_length=17, unique=True)  # ISBN, unique
    available = models.BooleanField(default=True)  
    published_date = models.DateField()  
    publisher = models.CharField(max_length=255)  
    genres = models.ManyToManyField(Genre, blank=True)  
    authors = models.ManyToManyField(Author)  
    borrower = models.OneToOneField(User, on_delete=models.SET_NULL, null=True, blank=True)
    
    def __str__(self):
        return self.title  
    

# tuple
BORROW_REQUEST_STATUS_CHOICES = (
    ('PENDING', 'Pending'),
    ('APPROVED', 'Approved'),
    ('COLLECTED', 'Collected'),
    ('COMPLETE', 'Complete'),
    ('DECLINED', 'Declined'),
)

class BorrowRequest(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    borrower = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.CharField(max_length=20, choices=BORROW_REQUEST_STATUS_CHOICES, default='PENDING')
    overdue = models.BooleanField(default=False)
    request_date = models.DateField()
    approval_date = models.DateField(null=True, blank=True)
    due_date = models.DateField(null=True, blank=True)
    complete_date = models.DateField(null=True, blank=True)

    def __str__(self):
         return f"Borrow request for {self.book.title}"
    

templates/author_form.html
{% extends "base.html" %}

{% block title %}Add Author{% endblock %}

{% block content %}
    <h1>Add Author</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-secondary btn-sm">Save</button>
    </form>
    <a href="{% url 'Books:author_list' %}" class="btn btn-secondary btn-sm">Back to Author List</a>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Library{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            background-image: url("https://images.pexels.com/photos/159872/book-open-pages-literature-159872.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1");
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-color: rgba(255, 255, 255, 0.9); 
        }
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="#">Library</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href={% url 'home' %}>Home</a>
                        <li class="nav-item">
                            <a class="nav-link"  href="{% url 'Users:login' %}">Login In</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link"  href="{% url 'Users:register' %}">Registration</a>
                        </li>

                    </li>
                    {% if not user.is_anonymous %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            Menu
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'Users:librarian_menu' %}">Librarian menu</a></li>
                            <li><a class="dropdown-item" href="{% url 'Books:book_list' %}">Books</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'Users:user_office' %}">User Office</a></li>
                            <li><a class="dropdown-item" href="{% url 'Books:search_results' %}">Search</a></li>
                            <li><a class="dropdown-item" href="{% url 'Users:logout' %}">Logout</a></li>
                            {% endif %}
                        </ul>
                    </li>
            
                </ul>
            </div>
        </div>
    </nav>
    








    <main class="container mt-4">
        {% block content %}{% endblock %}
    </main>
    <footer style="text-align: center; color: white;">
        <p>&copy; 2023 LIBRARY SYSTEM </p>
    </footer>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/book_detail.html
{% extends 'base.html' %}

{% block content %}
  <h2>Book Detail: {{ book.title }}</h2>
  <p><strong>Genre(s):</strong> {{ book.genres.all|join:", " }}</p>
  <p><strong>Author(s):</strong> {{ book.authors.all|join:", " }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Publication Date:</strong> {{ book.publication_date }}</p>
  <p><strong>Publisher:</strong> {{ book.publisher }}</p>
  <p><strong>Summary:</strong> {{ book.summary }}</p>

  <table class="table">
    <thead>
      <tr>
        <th>Status</th>
        <th>Due Date</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      {% if borrow_request %}
        <tr>
          <td>{{ borrow_request.get_status_display }}</td>
          {% if borrow_request.status == 'approve' %}
            <td>{{ borrow_request.due_date }}</td>
            <td>
              <form method="post">
                {% csrf_token %}
                <button type="submit" name="collect_book" class="btn btn-primary">Collect Book</button>
              </form>
            </td>
          {% elif borrow_request.status == 'completed' %}
            <td></td>
            <td>
              <form method="post">
                {% csrf_token %}
                <button type="submit" name="return_book" class="btn btn-success">Return Book</button>
              </form>
            </td>
          {% else %}
            <td></td>
            <td></td>
          {% endif %}
        </tr>
      {% else %}
        <tr>
          <td>Available</td>
          <td></td>
          <td>
            <form method="post">
              {% csrf_token %}
              <input type="number" name="borrow_days" placeholder="Borrow Days" required>
              <button type="submit" name="create_borrow_request" class="btn btn-primary">Request Borrow</button>
            </form>
          </td>
        </tr>
      {% endif %}
    </tbody>
  </table>

  <a href="{% url 'Books:book_list' %}" class="btn btn-secondary">Back to Book List</a>
  
{% endblock %}

templates/book_list.html
{% extends 'base.html' %}

{% block content %}
<footer style="text-align: center; color: white;">
    <h1> Book List </h1>
</footer>
    <table class="table ">
        <thead>
            <tr>
                <th>Title</th>
                <th>Authors</th>
                <th>Summary</th>
                <th>Status</th>
                <th>Actions</th>
                <th>       </th>
            </tr>
        </thead>
        <tbody>
            {% for book in books %}
                <tr>
                    <td><a href="{% url 'Books:book_detail' book.id %}" class="font-monospace text-dark">{{ book.title }} </a></td>
                    <td>{{ book.authors.all|join:", " }}</td>
                    <td>{{ book.summary }}</td>
                    <td>
                        {% if book.available %}
                            Available
                        {% else %}
                            Not Available
                        {% endif %}
                    </td>
                    <td>
                        <td>
                            {% if user_can_edit %}
                                <a href="{% url 'Books:update_book' book.id %}" class="btn btn-secondary ml-2">Update</a>
                                <a href="{% url 'Books:confirm_delete_book' book.id %}" class="btn btn-danger">Delete</a>
                            {% endif %}
                        </td>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/borrow_history.html
{% extends 'base.html' %}

{% block content %}
    <h1>Borrow History</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Book</th>
                <th>Status</th>
                <th>Request date</th>
                <th>Approval date</th>
                <!--add another -->
            </tr>
        </thead>
        <tbody>
            {% for request in borrow_requests %}
                <tr>
                    <td>{{ request.book.title }}</td>
                    <td>{{ request.get_status_display }}</td>
                    <td>{{ request.request_date }}</td>
                    <td>{{ request.approval_date }}</td>
                    <!-- add another -->
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/borrow_requests.html
{% extends 'base.html' %}

{% block content %}
    <h2>Borrow Requests</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Book Title</th>
                <th>Borrower</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for request in borrow_requests %}
                <tr>
                    <td>{{ request.book.title }}</td>
                    <td>{{ request.borrower.username }}</td>
                    <td>{{ request.get_status_display }}</td>
                    <td>
                        <form method="post">
                            {% csrf_token %}
                            <input type="hidden" name="request_id" value="{{ request.id }}">
                            <button type="submit" name="action" value="approve" class="btn btn-success">Approve</button>
                            <button type="submit" name="action" value="decline" class="btn btn-danger">Decline</button>
                            <button type="submit" name="action" value="delete" class="btn btn-warning">Delete</button>
                            
                            {% if request.status == 'returned' %}
                                <button type="submit" name="action" value="return" class="btn btn-info">Return</button>
                            {% endif %}
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/change_password.html
{% extends 'base.html' %}

{% block content %}
  <h2>Change Password</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-secondary btn-sm">Change Password</button>
  </form>
  <a href="{% url 'Users:user_office' %}" class="btn btn-secondary btn-sm">Back to User Office</a>
{% endblock %}

templates/edit_profile.html
{% extends 'base.html' %}

{% block content %}
  <h2>Edit Profile - {{ user.username }}</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-secondary btn-sm">Save Changes</button>
  </form>

  <div class="text mt-3">
    <a href="{% url 'Users:delete_profile' user.pk %}" class="btn btn-secondary btn-sm">Delete</a>
    <a href="{% url 'Users:change_password' %}" class="btn btn-secondary btn-sm">Change Password</a>
  </div>
{% endblock %}

templates/genre_edit.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-5">
    <h1 class="mb-4">Edit Genre</h1>
    <form method="post">
      {% csrf_token %}
      <div class="mb-3">
        {{ form.name.label_tag }}
        {{ form.name }}
      </div>
      <button type="submit" class="btn btn-secondary btn-sm">Save</button>
    </form>
    <form method="post" action="{% url 'Books:genre_delete' genre.pk %}" class="mt-3">
      {% csrf_token %}
      <button type="submit" class="btn btn-danger btn-sm">Delete Genre</button>
    </form>
  </div>
{% endblock %}

templates/genre_form.html
{% extends 'base.html' %}

{% block content %}
  <div class="container mt-5">
    <h1 class="mb-4">Add Genre</h1>
    <form method="post">
      {% csrf_token %}
      <div class="mb-3">
        {{ form.name.label_tag }}
        {{ form.name }}
      </div>
      <button type="submit" class="btn btn-secondary btn-sm">Save</button>
    </form>
  </div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block title %}Home - Library{% endblock %}

{% block content %}
<figure class="text-center">
    <figcaption class="blockquote-footer">
      Books alive <cite title="Source Title">WHEN YOU READ THEM</cite>
    </figcaption>
    <a href={% url 'home' %}> </a>
  </figure>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome to Library System</title>
    <style>
        body {
            background-image: url("https://trumpwallpapers.com/wp-content/uploads/Library-Wallpaper-40-3840x2560-1-scaled.jpg");
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
            margin: 0;
            padding: 0;
            height: 100vh;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }

        h1 {
            color: white;
            font-size: 36px;
            text-align: center;
        }

        a {
            color: white;
            font-size: 18px;
            text-decoration: none;
            margin-top: 20px;
        }
    </style>
</head>
<body>
    <h1>Welcome to Library System</h1>
    <a href="{% url 'home' %}">Go to Home Page(tap me)</a>
</body>
</html>

templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">{{ title }}</div>
                <div class="card-body">
                    {% if error_message %}
                    <div class="alert alert-danger">{{ error_message }}</div>
                    {% endif %}
                    <form method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="username" class="form-label"><em>Username</em></label>
                            <input type="text" class="form-control" id="username" name="username" required>
                        </div>
                        <div class="mb-3">
                            <label for="password" class="form-label"><em>Password</em></label>
                            <input type="password" class="form-control" id="password" name="password" required>
                        </div>
                        <button type="submit" class="w-100 btn btn-lg btn-outline-dark">Login</button>
                        <div class="mb-3 text-center">
                            <p>Don't have an account?</p>
                            <a href="{% url 'Users:register' %}" class="text-body fw-bold">Join us now</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/update_book.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h2>Update Book</h2>
                </div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-control form-control-sm">
                            <label for="{{ form.title.id_for_label }}">Title:</label>
                            {{ form.title }}
                        </div>
                        <div class="form-control form-control-sm">
                            <label for="{{ form.summary.id_for_label }}">Summary:</label>
                            {{ form.summary }}
                        </div>
                        <div class="form-control form-control-sm">
                            <label for="{{ form.isbn.id_for_label }}">ISBN:</label>
                            {{ form.isbn }}
                        </div>
                        <div class="form-control form-control-sm">
                            <label for="{{ form.available.id_for_label }}">Available:</label>
                            {{ form.available }}
                        </div>
                        <div class="form-control form-control-sm">
                            <label for="{{ form.published_date.id_for_label }}">Published Date:</label>
                            {{ form.published_date }}
                        </div>
                        <div class="form-control form-control-sm">
                            <label for="{{ form.publisher.id_for_label }}">Publisher:</label>
                            {{ form.publisher }}
                        </div>
                        <div class="form-control form-control-sm">
                            <label for="{{ form.genres.id_for_label }}">Genres:</label>
                            {{ form.genres }}
                        </div>
                        <div class="form-control form-control-sm">
                            <label for="{{ form.authors.id_for_label }}">Authors:</label>
                            {{ form.authors }}
                        </div>
                        <button type="submit" class="btn btn-primary">Update</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}